### ISSUE TITLE
atomic run weather-100-atomicapp does not work

### ISSUE THREAD

**Issue by goern** [goern/weather#1]
```
$ atomic run docker-registry:5000/goern/weather-100-atomicapp 
docker run -it --rm --privileged --net=host -v `pwd`:/atomicapp -v /run:/run -v /:/host --name weather-100-atomicapp -e NAME=weather-100-atomicapp -e IMAGE=docker-registry:5000/goern/weather-100-atomicapp docker-registry:5000/goern/weather-100-atomicapp -v run /atomicapp
2015-05-14 03:24:32,752 - atomicapp.install - INFO - App name is docker-registry:5000/goern/weather-100-atomicapp, will be populated to /atomicapp
2015-05-14 03:24:32,753 - atomicapp.utils - DEBUG - {'provider': 'kubernetes'}
2015-05-14 03:24:32,869 - atomicapp.utils - DEBUG - Output of docker images cmd: 2e096ceda3b7

2015-05-14 03:24:32,869 - atomicapp.utils - DEBUG - Image docker-registry:5000/goern/weather-100-atomicapp already present with id 2e096ceda3b7. Use --update to re-pull.
2015-05-14 03:24:32,869 - atomicapp.utils - DEBUG - {'provider': 'kubernetes'}
FATA[0000] Error response from daemon: Conflict. The name "weather-100-atomicapp" is already in use by container 3e8c4f15974d. You have to delete (or rename) that container to be able to reuse that name. 
2015-05-14 03:24:32,884 - atomicapp.utils - INFO - Using temporary directory /tmp/appent-weather-100-atomicapp0qEbGt
2015-05-14 03:24:32,885 - atomicapp.install - DEBUG - ['docker', 'cp', 'weather-100-atomicapp:/application-entity', '/tmp/appent-weather-100-atomicapp0qEbGt']
2015-05-14 03:24:32,897 - atomicapp.install - DEBUG - Application entity data copied to /tmp/appent-weather-100-atomicapp0qEbGt
Error response from daemon: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f
FATA[0000] Error: failed to remove one or more containers 
2015-05-14 03:24:32,909 - atomicapp.install - DEBUG - nulecule path for pulled image: /tmp/appent-weather-100-atomicapp0qEbGt/application-entity/nulecule
2015-05-14 03:24:32,913 - atomicapp.params - DEBUG - Setting app id to atomicapp-weather-100
2015-05-14 03:24:32,914 - atomicapp.install - DEBUG - App ID: atomicapp-weather-100
2015-05-14 03:24:32,914 - atomicapp.install - INFO - Copying app weather-100-atomicapp
2015-05-14 03:24:32,915 - atomicapp.utils - DEBUG - Provider: kubernetes
2015-05-14 03:24:32,915 - atomicapp.utils - DEBUG - Artifact file://artifacts/kubernetes/redis-master-service.json: OK
2015-05-14 03:24:32,915 - atomicapp.utils - DEBUG - Artifact file://artifacts/kubernetes/redis-master-controller.json: OK
2015-05-14 03:24:32,915 - atomicapp.utils - INFO - Artifacts for weather-100-atomicapp present for these providers: kubernetes
2015-05-14 03:24:32,915 - atomicapp.utils - DEBUG - No artifacts for weather-frontend-atomicapp
2015-05-14 03:24:32,915 - atomicapp.utils - INFO - Artifacts for weather-frontend-atomicapp present for these providers: 
2015-05-14 03:24:32,915 - atomicapp.utils - DEBUG - No artifacts for kubernetes
2015-05-14 03:24:32,915 - atomicapp.utils - INFO - Artifacts for kubernetes present for these providers: 
2015-05-14 03:24:32,915 - atomicapp.install - INFO - Installing dependencies for atomicapp-weather-100
2015-05-14 03:24:32,915 - atomicapp.utils - DEBUG - {u'artifacts': {u'kubernetes': [u'file://artifacts/kubernetes/redis-master-service.json', u'file://artifacts/kubernetes/redis-master-controller.json']}}
2015-05-14 03:24:32,916 - atomicapp.install - DEBUG - Component weather-100-atomicapp is part of the app
2015-05-14 03:24:32,916 - atomicapp.install - DEBUG - Values: {u'weather-100-atomicapp': {}}
2015-05-14 03:24:32,916 - atomicapp.utils - DEBUG - {u'source': u'docker://goern/weather-frontend-atomicapp'}
2015-05-14 03:24:32,916 - atomicapp.install - INFO - Component weather-frontend-atomicapp is external dependency
2015-05-14 03:24:32,916 - atomicapp.install - DEBUG - Component path: /atomicapp/external/weather-frontend-atomicapp
2015-05-14 03:24:32,916 - atomicapp.install - INFO - Pulling goern/weather-frontend-atomicapp
2015-05-14 03:24:32,916 - atomicapp.install - INFO - App name is goern/weather-frontend-atomicapp, will be populated to /atomicapp/external/weather-frontend-atomicapp
2015-05-14 03:24:32,916 - atomicapp.params - DEBUG - Data given {'general': {'provider': 'kubernetes'}}
2015-05-14 03:24:32,916 - atomicapp.utils - DEBUG - {'provider': 'kubernetes'}
2015-05-14 03:24:32,970 - atomicapp.utils - DEBUG - Output of docker images cmd: 
Trying to pull repository docker-registry:5000/goern/weather-frontend-atomicapp ...
538c2f706f62: Download complete 
6941bfcbbfca: Download complete 
41459f052977: Download complete 
fd44297e2ddb: Download complete 
b4ed7e5c81c4: Download complete 
b156433157f8: Download complete 
5fa756cdff85: Download complete 
cd7d1b8b26d9: Download complete 
0be5e3e55229: Download complete 
50b92dfa1f9e: Download complete 
8170321dee7d: Download complete 
104b2c2ff7d3: Download complete 
ad12bfd46b45: Download complete 
1c03e9ba2725: Download complete 
332c7b2ff756: Download complete 
7b3c0780d5b6: Download complete 
c6981dbdbd01: Download complete 
09eee4649d60: Download complete 
6d2170c94b83: Download complete 
98c6f172812b: Download complete 
Status: Image is up to date for docker-registry:5000/goern/weather-frontend-atomicapp:latest
2015-05-14 03:24:37,016 - atomicapp.utils - DEBUG - {'provider': 'kubernetes'}
625dda0777260b4f60d00893e8c0d0629cc96d59136ef2f1087d743f6f44a70a
2015-05-14 03:24:40,034 - atomicapp.utils - INFO - Using temporary directory /tmp/appent-weather-frontend-atomicappUiJnLa
2015-05-14 03:24:40,034 - atomicapp.install - DEBUG - ['docker', 'cp', u'weather-frontend-atomicapp:/application-entity', u'/tmp/appent-weather-frontend-atomicappUiJnLa']
2015-05-14 03:24:40,726 - atomicapp.install - DEBUG - Application entity data copied to /tmp/appent-weather-frontend-atomicappUiJnLa
weather-frontend-atomicapp
2015-05-14 03:24:43,947 - atomicapp.install - DEBUG - nulecule path for pulled image: /tmp/appent-weather-frontend-atomicappUiJnLa/application-entity/nulecule
2015-05-14 03:24:43,950 - atomicapp.params - DEBUG - Setting app id to atomicapp-weather-frontend-100
2015-05-14 03:24:43,950 - atomicapp.install - DEBUG - App ID: atomicapp-weather-frontend-100
2015-05-14 03:24:43,950 - atomicapp.install - INFO - Copying app weather-frontend-atomicapp
2015-05-14 03:24:43,952 - atomicapp.utils - DEBUG - Provider: kubernetes
2015-05-14 03:24:43,952 - atomicapp.utils - DEBUG - Artifact file://artifacts/kubernetes/frontend-service.json: OK
2015-05-14 03:24:43,952 - atomicapp.utils - DEBUG - Artifact file://artifacts/kubernetes/frontend-pod.json: OK
2015-05-14 03:24:43,952 - atomicapp.utils - INFO - Artifacts for weather-frontend-atomicapp present for these providers: kubernetes
2015-05-14 03:24:43,953 - atomicapp.utils - DEBUG - No artifacts for kubernetes
2015-05-14 03:24:43,953 - atomicapp.utils - INFO - Artifacts for kubernetes present for these providers: 
2015-05-14 03:24:43,953 - atomicapp.install - INFO - Installing dependencies for atomicapp-weather-frontend-100
2015-05-14 03:24:43,953 - atomicapp.utils - DEBUG - {u'artifacts': {u'kubernetes': [u'file://artifacts/kubernetes/frontend-service.json', u'file://artifacts/kubernetes/frontend-pod.json']}}
2015-05-14 03:24:43,953 - atomicapp.install - DEBUG - Component weather-frontend-atomicapp is part of the app
2015-05-14 03:24:43,953 - atomicapp.install - DEBUG - Values: {u'weather-frontend-atomicapp': {}}
2015-05-14 03:24:43,953 - atomicapp.utils - DEBUG - {u'labels': [u'redis', u'weather', u'frontend']}
2015-05-14 03:24:43,953 - atomicapp.install - DEBUG - Component kubernetes is part of the app
2015-05-14 03:24:43,953 - atomicapp.install - DEBUG - Values: {u'weather-frontend-atomicapp': {}, u'kubernetes': {}}
2015-05-14 03:24:43,953 - atomicapp.install - DEBUG - {u'weather-frontend-atomicapp': {}, u'kubernetes': {}}
2015-05-14 03:24:43,953 - atomicapp.params - DEBUG - Data given {u'weather-frontend-atomicapp': {}, u'kubernetes': {}}
2015-05-14 03:24:43,953 - atomicapp.install - DEBUG - {u'weather-frontend-atomicapp': {}, u'kubernetes': {}, 'general': {'provider': 'kubernetes'}}
2015-05-14 03:24:43,953 - atomicapp.install - INFO - Component installed into /atomicapp/external/weather-frontend-atomicapp
2015-05-14 03:24:43,953 - atomicapp.utils - DEBUG - {u'labels': [u'redis', u'weather']}
2015-05-14 03:24:43,953 - atomicapp.install - DEBUG - Component kubernetes is part of the app
2015-05-14 03:24:43,953 - atomicapp.install - DEBUG - Values: {u'weather-100-atomicapp': {}, u'weather-frontend-atomicapp': {}, u'kubernetes': {}}
2015-05-14 03:24:43,953 - atomicapp.install - DEBUG - {u'weather-100-atomicapp': {}, u'weather-frontend-atomicapp': {}, u'kubernetes': {}}
2015-05-14 03:24:43,953 - atomicapp.params - DEBUG - Data given {u'weather-100-atomicapp': {}, u'weather-frontend-atomicapp': {}, u'kubernetes': {}}
2015-05-14 03:24:43,953 - atomicapp.install - DEBUG - {u'weather-frontend-atomicapp': {}, u'kubernetes': {}, 'general': {'provider': 'kubernetes'}}
blah
2015-05-14 03:24:43,953 - atomicapp.params - INFO - Writing answers file template to /atomicapp/answers.conf.sample
2015-05-14 03:24:43,954 - atomicapp.plugin - DEBUG - Loading providers from /usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/openshift.py:1: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  from atomicapp.plugin import Provider
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/openshift.py:3: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  from collections import OrderedDict
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/openshift.py:5: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  import os, subprocess
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/openshift.py:6: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  import anymarkup
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/openshift.py:7: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  import logging
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/docker.py:1: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  from atomicapp.plugin import Provider
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/docker.py:2: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  import os, subprocess
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/docker.py:4: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  import logging
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/kubernetes.py:1: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  from atomicapp.plugin import Provider
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/kubernetes.py:3: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  from collections import OrderedDict
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/kubernetes.py:4: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  import os, anymarkup, subprocess
/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/kubernetes.py:6: RuntimeWarning: Parent module 'atomicapp.providers' not found while handling absolute import
  import logging
2015-05-14 03:24:43,959 - atomicapp.params - DEBUG - Setting app id to atomicapp-weather-100
2015-05-14 03:24:43,959 - atomicapp.utils - DEBUG - Provider: kubernetes
2015-05-14 03:24:43,959 - atomicapp.utils - DEBUG - Artifact file://artifacts/kubernetes/redis-master-service.json: OK
2015-05-14 03:24:43,959 - atomicapp.utils - DEBUG - Artifact file://artifacts/kubernetes/redis-master-controller.json: OK
2015-05-14 03:24:43,959 - atomicapp.utils - INFO - Artifacts for weather-100-atomicapp present for these providers: kubernetes
2015-05-14 03:24:43,959 - atomicapp.utils - DEBUG - No artifacts for weather-frontend-atomicapp
2015-05-14 03:24:43,960 - atomicapp.utils - INFO - Artifacts for weather-frontend-atomicapp present for these providers: 
2015-05-14 03:24:43,960 - atomicapp.utils - DEBUG - No artifacts for kubernetes
2015-05-14 03:24:43,960 - atomicapp.utils - INFO - Artifacts for kubernetes present for these providers: 
2015-05-14 03:24:43,960 - atomicapp.utils - DEBUG - {u'artifacts': {u'kubernetes': [u'file://artifacts/kubernetes/redis-master-service.json', u'file://artifacts/kubernetes/redis-master-controller.json']}}
2015-05-14 03:24:43,960 - atomicapp.run - DEBUG - Processing component weather-100-atomicapp
2015-05-14 03:24:43,961 - atomicapp.utils - INFO - Using temporary directory /tmp/appent-atomicapp-weather-10066i6zj
2015-05-14 03:24:43,961 - atomicapp.run - DEBUG - Templating artifact /atomicapp/artifacts/kubernetes/redis-master-service.json
2015-05-14 03:24:43,961 - atomicapp.params - DEBUG - Param provider already in general with value kubernetes
2015-05-14 03:24:43,961 - atomicapp.run - DEBUG - Config: {'provider': 'kubernetes'} 
2015-05-14 03:24:43,961 - atomicapp.run - DEBUG - {'provider': 'kubernetes'}
2015-05-14 03:24:43,961 - atomicapp.run - DEBUG - Writing artifact to /tmp/appent-atomicapp-weather-10066i6zj/weather-100-atomicapp/artifacts/kubernetes/redis-master-service.json
2015-05-14 03:24:43,961 - atomicapp.run - DEBUG - Templating artifact /atomicapp/artifacts/kubernetes/redis-master-controller.json
2015-05-14 03:24:43,961 - atomicapp.params - DEBUG - Param provider already in general with value kubernetes
2015-05-14 03:24:43,962 - atomicapp.run - DEBUG - Config: {'provider': 'kubernetes'} 
2015-05-14 03:24:43,962 - atomicapp.run - DEBUG - {'provider': 'kubernetes'}
2015-05-14 03:24:43,962 - atomicapp.run - DEBUG - Writing artifact to /tmp/appent-atomicapp-weather-10066i6zj/weather-100-atomicapp/artifacts/kubernetes/redis-master-controller.json
2015-05-14 03:24:43,962 - atomicapp.plugin - DEBUG - docker
2015-05-14 03:24:43,962 - atomicapp.plugin - DEBUG - openshift
2015-05-14 03:24:43,962 - atomicapp.plugin - DEBUG - kubernetes
2015-05-14 03:24:43,962 - atomicapp.plugin - DEBUG - Found provider atomicapp.providers.kubernetes.KubernetesProvider
2015-05-14 03:24:43,962 - atomicapp.params - DEBUG - Param provider already in general with value kubernetes
2015-05-14 03:24:43,962 - atomicapp.run - INFO - Using provider kubernetes for component weather-100-atomicapp
2015-05-14 03:24:43,963 - atomicapp.providers.kubernetes - DEBUG - /tmp/appent-atomicapp-weather-10066i6zj/weather-100-atomicapp/artifacts/kubernetes/redis-master-service.json
2015-05-14 03:24:43,963 - atomicapp.providers.kubernetes - DEBUG - /tmp/appent-atomicapp-weather-10066i6zj/weather-100-atomicapp/artifacts/kubernetes/redis-master-controller.json
2015-05-14 03:24:43,963 - atomicapp.providers.kubernetes - INFO - Calling: /host/usr/bin/kubectl create -f /tmp/appent-atomicapp-weather-10066i6zj/weather-100-atomicapp/artifacts/kubernetes/redis-master-service.json
services/redis-master
2015-05-14 03:24:43,985 - atomicapp.providers.kubernetes - INFO - Calling: /host/usr/bin/kubectl create -f /tmp/appent-atomicapp-weather-10066i6zj/weather-100-atomicapp/artifacts/kubernetes/redis-master-controller.json
replicationcontrollers/redis-master
2015-05-14 03:24:44,018 - atomicapp.utils - DEBUG - {u'source': u'docker://goern/weather-frontend-atomicapp'}
2015-05-14 03:24:44,018 - atomicapp.install - INFO - App name is docker-registry:5000/goern/weather-100-atomicapp, will be populated to /atomicapp
2015-05-14 03:24:44,018 - atomicapp.utils - DEBUG - {'provider': 'kubernetes'}
2015-05-14 03:24:44,418 - atomicapp.utils - DEBUG - Output of docker images cmd: 2e096ceda3b7

2015-05-14 03:24:44,418 - atomicapp.utils - DEBUG - Image docker-registry:5000/goern/weather-100-atomicapp already present with id 2e096ceda3b7. Use --update to re-pull.
2015-05-14 03:24:44,418 - atomicapp.utils - DEBUG - {'provider': 'kubernetes'}
FATA[0000] Error response from daemon: Conflict. The name "weather-100-atomicapp" is already in use by container 3e8c4f15974d. You have to delete (or rename) that container to be able to reuse that name. 
2015-05-14 03:24:44,593 - atomicapp.utils - INFO - Using temporary directory /tmp/appent-weather-100-atomicappezO2Bd
2015-05-14 03:24:44,593 - atomicapp.install - DEBUG - ['docker', 'cp', 'weather-100-atomicapp:/application-entity', '/tmp/appent-weather-100-atomicappezO2Bd']
2015-05-14 03:24:44,945 - atomicapp.install - DEBUG - Application entity data copied to /tmp/appent-weather-100-atomicappezO2Bd
Error response from daemon: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f
FATA[0000] Error: failed to remove one or more containers 
2015-05-14 03:24:45,135 - atomicapp.install - DEBUG - nulecule path for pulled image: /tmp/appent-weather-100-atomicappezO2Bd/application-entity/nulecule
2015-05-14 03:24:45,139 - atomicapp.params - DEBUG - Setting app id to atomicapp-weather-100
2015-05-14 03:24:45,139 - atomicapp.install - DEBUG - App ID: atomicapp-weather-100
2015-05-14 03:24:45,139 - atomicapp.install - INFO - Copying app weather-100-atomicapp
2015-05-14 03:24:45,139 - atomicapp.utils - DEBUG - Provider: kubernetes
2015-05-14 03:24:45,139 - atomicapp.utils - DEBUG - Artifact file://artifacts/kubernetes/redis-master-service.json: OK
2015-05-14 03:24:45,139 - atomicapp.utils - DEBUG - Artifact file://artifacts/kubernetes/redis-master-controller.json: OK
2015-05-14 03:24:45,139 - atomicapp.utils - INFO - Artifacts for weather-100-atomicapp present for these providers: kubernetes
2015-05-14 03:24:45,139 - atomicapp.utils - DEBUG - No artifacts for weather-frontend-atomicapp
2015-05-14 03:24:45,139 - atomicapp.utils - INFO - Artifacts for weather-frontend-atomicapp present for these providers: 
2015-05-14 03:24:45,139 - atomicapp.utils - DEBUG - No artifacts for kubernetes
2015-05-14 03:24:45,139 - atomicapp.utils - INFO - Artifacts for kubernetes present for these providers: 
2015-05-14 03:24:45,139 - atomicapp.install - INFO - Installing dependencies for atomicapp-weather-100
2015-05-14 03:24:45,140 - atomicapp.utils - DEBUG - {u'artifacts': {u'kubernetes': [u'file://artifacts/kubernetes/redis-master-service.json', u'file://artifacts/kubernetes/redis-master-controller.json']}}
2015-05-14 03:24:45,140 - atomicapp.install - DEBUG - Component weather-100-atomicapp is part of the app
2015-05-14 03:24:45,140 - atomicapp.install - DEBUG - Values: {u'weather-100-atomicapp': {}}
2015-05-14 03:24:45,140 - atomicapp.utils - DEBUG - {u'source': u'docker://goern/weather-frontend-atomicapp'}
2015-05-14 03:24:45,140 - atomicapp.install - INFO - Component weather-frontend-atomicapp is external dependency
2015-05-14 03:24:45,140 - atomicapp.install - DEBUG - Component path: /atomicapp/external/weather-frontend-atomicapp
2015-05-14 03:24:45,140 - atomicapp.install - INFO - Component weather-frontend-atomicapp already exists at /atomicapp/external/weather-frontend-atomicapp - remove the directory or use --update option
2015-05-14 03:24:45,140 - atomicapp.utils - DEBUG - {u'labels': [u'redis', u'weather']}
2015-05-14 03:24:45,140 - atomicapp.install - DEBUG - Component kubernetes is part of the app
2015-05-14 03:24:45,140 - atomicapp.install - DEBUG - Values: {u'weather-100-atomicapp': {}, u'kubernetes': {}}
2015-05-14 03:24:45,140 - atomicapp.install - DEBUG - {u'weather-100-atomicapp': {}, u'kubernetes': {}}
2015-05-14 03:24:45,140 - atomicapp.params - DEBUG - Data given {u'weather-100-atomicapp': {}, u'kubernetes': {}}
2015-05-14 03:24:45,140 - atomicapp.install - DEBUG - {u'weather-100-atomicapp': {}, u'weather-frontend-atomicapp': {}, u'kubernetes': {}, 'general': {'provider': 'kubernetes'}}
blah
2015-05-14 03:24:45,140 - atomicapp.params - INFO - Writing answers file template to /atomicapp/answers.conf.sample
2015-05-14 03:24:45,140 - atomicapp.plugin - DEBUG - Loading providers from /usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers
2015-05-14 03:24:45,143 - atomicapp.params - DEBUG - Setting app id to atomicapp-weather-100
2015-05-14 03:24:45,144 - atomicapp.utils - DEBUG - Provider: kubernetes
2015-05-14 03:24:45,144 - atomicapp.utils - DEBUG - Artifact file://artifacts/kubernetes/redis-master-service.json: OK
2015-05-14 03:24:45,144 - atomicapp.utils - DEBUG - Artifact file://artifacts/kubernetes/redis-master-controller.json: OK
2015-05-14 03:24:45,144 - atomicapp.utils - INFO - Artifacts for weather-100-atomicapp present for these providers: kubernetes
2015-05-14 03:24:45,144 - atomicapp.utils - DEBUG - No artifacts for weather-frontend-atomicapp
2015-05-14 03:24:45,144 - atomicapp.utils - INFO - Artifacts for weather-frontend-atomicapp present for these providers: 
2015-05-14 03:24:45,144 - atomicapp.utils - DEBUG - No artifacts for kubernetes
2015-05-14 03:24:45,144 - atomicapp.utils - INFO - Artifacts for kubernetes present for these providers: 
2015-05-14 03:24:45,144 - atomicapp.utils - DEBUG - {u'artifacts': {u'kubernetes': [u'file://artifacts/kubernetes/redis-master-service.json', u'file://artifacts/kubernetes/redis-master-controller.json']}}
2015-05-14 03:24:45,144 - atomicapp.run - DEBUG - Processing component weather-100-atomicapp
2015-05-14 03:24:45,144 - atomicapp.utils - INFO - Using temporary directory /tmp/appent-atomicapp-weather-100yrRAvO
2015-05-14 03:24:45,144 - atomicapp.run - DEBUG - Templating artifact /atomicapp/artifacts/kubernetes/redis-master-service.json
2015-05-14 03:24:45,144 - atomicapp.params - DEBUG - Param provider already in general with value kubernetes
2015-05-14 03:24:45,144 - atomicapp.run - DEBUG - Config: {'provider': 'kubernetes'} 
2015-05-14 03:24:45,144 - atomicapp.run - DEBUG - {'provider': 'kubernetes'}
2015-05-14 03:24:45,144 - atomicapp.run - DEBUG - Writing artifact to /tmp/appent-atomicapp-weather-100yrRAvO/weather-100-atomicapp/artifacts/kubernetes/redis-master-service.json
2015-05-14 03:24:45,145 - atomicapp.run - DEBUG - Templating artifact /atomicapp/artifacts/kubernetes/redis-master-controller.json
2015-05-14 03:24:45,145 - atomicapp.params - DEBUG - Param provider already in general with value kubernetes
2015-05-14 03:24:45,145 - atomicapp.run - DEBUG - Config: {'provider': 'kubernetes'} 
2015-05-14 03:24:45,145 - atomicapp.run - DEBUG - {'provider': 'kubernetes'}
2015-05-14 03:24:45,145 - atomicapp.run - DEBUG - Writing artifact to /tmp/appent-atomicapp-weather-100yrRAvO/weather-100-atomicapp/artifacts/kubernetes/redis-master-controller.json
2015-05-14 03:24:45,145 - atomicapp.plugin - DEBUG - docker
2015-05-14 03:24:45,145 - atomicapp.plugin - DEBUG - openshift
2015-05-14 03:24:45,146 - atomicapp.plugin - DEBUG - kubernetes
2015-05-14 03:24:45,146 - atomicapp.plugin - DEBUG - Found provider atomicapp.providers.kubernetes.KubernetesProvider
2015-05-14 03:24:45,146 - atomicapp.params - DEBUG - Param provider already in general with value kubernetes
2015-05-14 03:24:45,146 - atomicapp.run - INFO - Using provider kubernetes for component weather-100-atomicapp
2015-05-14 03:24:45,176 - atomicapp.providers.kubernetes - DEBUG - /tmp/appent-atomicapp-weather-100yrRAvO/weather-100-atomicapp/artifacts/kubernetes/redis-master-service.json
2015-05-14 03:24:45,177 - atomicapp.providers.kubernetes - DEBUG - /tmp/appent-atomicapp-weather-100yrRAvO/weather-100-atomicapp/artifacts/kubernetes/redis-master-controller.json
2015-05-14 03:24:45,177 - atomicapp.providers.kubernetes - INFO - Calling: /host/usr/bin/kubectl create -f /tmp/appent-atomicapp-weather-100yrRAvO/weather-100-atomicapp/artifacts/kubernetes/redis-master-service.json
Error: service "redis-master" already exists
Traceback (most recent call last):
  File "/usr/bin/atomicapp", line 9, in <module>
    load_entry_point('atomicapp==0.1', 'console_scripts', 'atomicapp')()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/cli/main.py", line 101, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/cli/main.py", line 83, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/cli/main.py", line 32, in cli_run
    ae.run()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/run.py", line 158, in run
    self._dispatchGraph()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/run.py", line 75, in _dispatchGraph
    ret = component_run.run()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/run.py", line 158, in run
    self._dispatchGraph()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/run.py", line 79, in _dispatchGraph
    self._processComponent(component, graph_item)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/run.py", line 147, in _processComponent
    provider.deploy()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/kubernetes.py", line 44, in deploy
    self._callK8s(k8s_file)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/providers/kubernetes.py", line 25, in _callK8s
    subprocess.check_call(cmd) == 0
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/host/usr/bin/kubectl', 'create', '-f', u'/tmp/appent-atomicapp-weather-100yrRAvO/weather-100-atomicapp/artifacts/kubernetes/redis-master-service.json']' returned non-zero exit status 1
```

**Comment by goern** [comment]
I have created all the required docker images at https://hub.docker.com/u/goern/
